### ISSUE TITLE
Maven repo | 500 - Internal Server Error

### ISSUE THREAD

**Issue by games647** [Mitsugaru/PlayerPoints#12]
When I try to access the maven repo I get a 500 status code.

**Comment by Mitsugaru** [comment]
Hey @games647 

Thanks for notifying me. Can you try and see if you are able to access it now?

**Comment by games647** [comment]
Yes it works now. Thanks for the quick support.

**Comment by games647** [comment]
Your repository is down again with a 502.

**Comment by Mitsugaru** [comment]
Ah yeah, the host had to do some migration.
Maybe some day I'll actually have it auto-start on startup, but for now its a manual thing.
