### ISSUE TITLE
Can not use MySQL

### ISSUE THREAD

**Issue by xyblues** [Mitsugaru/PlayerPoints#13]
![image](https://cloud.githubusercontent.com/assets/15712089/13833743/819b819c-ec23-11e5-8673-6069a875fb83.png)

Why？

storage: MySQL
mysql:
  host: localhost
  port: 3306
  database: playerpoints
  user: root
  password: *******
  table: playerpoints
  import:
    use: false
    source: YAML
  export:
    use: false
    source: SQLITE
  retry: 10
vote:
  enabled: false
  amount: 100
  online: false
restrictions:
  autocompleteOnline: false
  hasPlayedBefore: false
debug:
  database: false
  uuid: false
vault: false
version: 2.1.4

**Comment by Mitsugaru** [comment]
You are missing the [SQLibrary](http://dev.bukkit.org/bukkit-plugins/sqlibrary/) dependency. If you want MySQL support, you need to add the library to your plugins folder.
