### ISSUE TITLE
Fail Code source

### ISSUE THREAD

**Issue by FredericFernandes** [Mitsugaru/PlayerPoints#20]
Into File org.black_ixx.playerpoints.storage.exports.SQLiteExport

[at ligne 43](https://github.com/Mitsugaru/PlayerPoints/blob/master/src/org/black_ixx/playerpoints/storage/exports/SQLiteExport.java#L43)

`query = sqlite.query("SELECT * FROM playerpoints");`

is not  
`query = sqlite.query(String.format("SELECT * FROM %s", config.table));`

??

**Comment by FredericFernandes** [comment]
Same error : [here](https://github.com/Mitsugaru/PlayerPoints/blob/master/src/org/black_ixx/playerpoints/storage/imports/SQLiteImport.java#L45)

**Comment by Mitsugaru** [comment]
That is correct, we do not rename the table for SQLite. Table name is only for MySQL-based databases that require something different from the standard for outside applications to read from.

Is there an issue with the SQLite exporter? It's been a while since I tested it.

**Comment by FredericFernandes** [comment]
hoo , okey .
Sry but i use only MySQL , i'ts not a problem so .
