### ISSUE TITLE
Still not working to use Mysql

### ISSUE THREAD

**Issue by partydragen** [Mitsugaru/PlayerPoints#21]
I really need this on my Network but can't when MySql Storage not working :/
Error log http://pastebin.com/SAJJqs1d

**Comment by Mitsugaru** [comment]
You are missing the [SQLibrary](https://dev.bukkit.org/bukkit-plugins/sqlibrary/) dependency. We have not moved over to using Bukkit database API, so until that happens SQLibrary is a requirement for MySQL support with this plugin.

**Comment by partydragen** [comment]
@Mitsugaru yea i found that out after reading the other issuses :P

But can you please change over to Bukkit Database api as fast u can?
May want to setup this on my network tomorrow but i really don't want SQLibrary :/

And i goes to get my developers to create a shop gui on my core plugin and then using this api
Don't want to use Bossshop, U know other than bosshop?

**Comment by Mitsugaru** [comment]
Honestly, I haven't really done any work on this and don't plan to. I've been busy with work and other projects and have left Minecraft plugin development for quite a while now.
