### ISSUE TITLE
Command to save the storage to disk

### ISSUE THREAD

**Issue by totokaka** [Mitsugaru/PlayerPoints#23]
There should be a command to save the player points storage to disk. This is relevant especially for the YAML backend, but also for the sqlite backend.

Aditionally, it would be nice to be able to configure an auto-backup interval to run in the background.

I plan to submit a PR implementing these features.

**Comment by totokaka** [comment]
After digging in the code, I see that when using the YAML storage, the points are stored to disk every time a player's points are changed, *on the main thread*. This is really bad practice, and is the same problem as #5.

I will instead make a PR that does this save in a separate thread.

**Comment by Mitsugaru** [comment]
To be honest, if it isn't already apparent, I've not been able to maintain or improve PlayerPoints for some years now. I kinda moved away from the Minecraft / Bukkit / Spigot scene as I no longer had the time to put towards working on the plugins. That and having moved onto different games, I really don't see myself returning to the Minecraft mod / plugin scene any time in the near future.

Still haven't bothered to recreate the Jenkins instance I used to have that would auto build and publish all my plugin repos.

So, kudos on the effort. I've merged it into the main but in all honesty at this point of time the project ought to live in on in a fork that is maintained and active.

**Comment by Blackixx** [comment]
If I get the time I'l move PlayerPoints from Bukkit to Spigot and work on updates, however of course I would be happy in case anyone else should be willing to put time into updates and plugin improvements.

In case anyone wants to maintain PlayerPoints on Spigot and @Mitsugaru approves it I would be fine with that and provide help.

**Comment by tlaundal** [comment]
Thanks for merging.
It's not really important to me that this gets incorporated into an actual release, I just share an improvement I found essential for my use.

I totally understand moving on to other things, but congrats on creating a fine plugin that still works many Minecraft and Bukkit versions later, @Mitsugaru and @Blackixx.

I do not have the capacity to mantain this plugin, but might come with a couple more bug fixes and improvements if I find something else that I need.
